aliases: []
creation_timestamp: 1724743026233
current_stage: None
description: null
last_updated_timestamp: 1724743026233
name: U_Net
run_id: 76e9bd74d51d473da738d3e8ceb3bbab
run_link: null
source: /home/zhazzouri/speech-music-classification-unet//mlflow/983643993131039407/76e9bd74d51d473da738d3e8ceb3bbab/artifacts/model
status: READY
status_message: null
storage_location: /home/zhazzouri/speech-music-classification-unet//mlflow/983643993131039407/76e9bd74d51d473da738d3e8ceb3bbab/artifacts/model
user_id: null
version: 14
