aliases: []
creation_timestamp: 1724686055910
current_stage: None
description: null
last_updated_timestamp: 1724686055910
name: U_Net
run_id: 48a69906d98a416f986fe4c27b114a9e
run_link: null
source: /home/zhazzouri/speech-music-classification-unet//mlflow/227176237394417399/48a69906d98a416f986fe4c27b114a9e/artifacts/model
status: READY
status_message: null
storage_location: /home/zhazzouri/speech-music-classification-unet//mlflow/227176237394417399/48a69906d98a416f986fe4c27b114a9e/artifacts/model
user_id: null
version: 1
