aliases: []
creation_timestamp: 1713559114147
current_stage: None
description: null
last_updated_timestamp: 1713559114147
name: U_Net
run_id: 6413ea714ddf4fd78d31e854a03cc312
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/993479011557489331/6413ea714ddf4fd78d31e854a03cc312/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/993479011557489331/6413ea714ddf4fd78d31e854a03cc312/artifacts/model
user_id: null
version: 1
