artifact_uri: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/993479011557489331/ba6c19146be74ef1bb71eaf453efb3b3/artifacts
end_time: 1715542867994
entry_point_name: ''
experiment_id: '993479011557489331'
lifecycle_stage: active
run_id: ba6c19146be74ef1bb71eaf453efb3b3
run_name: UNet_MFCCs 500 ms seconds learning decay
run_uuid: ba6c19146be74ef1bb71eaf453efb3b3
source_name: ''
source_type: 4
source_version: ''
start_time: 1715538033233
status: 3
tags: []
user_id: zainhazzouri
