artifact_uri: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/993479011557489331/dfe01de08ed74f8cb682c31b8f691ef1/artifacts
deleted_time: 1715762616045
end_time: null
entry_point_name: ''
experiment_id: '993479011557489331'
lifecycle_stage: deleted
run_id: dfe01de08ed74f8cb682c31b8f691ef1
run_name: grandiose-worm-813
run_uuid: dfe01de08ed74f8cb682c31b8f691ef1
source_name: ''
source_type: 4
source_version: ''
start_time: 1715707151832
status: 1
tags: []
user_id: zainhazzouri
