aliases: []
creation_timestamp: 1717443375697
current_stage: None
description: null
last_updated_timestamp: 1717443375697
name: AttentionUNet
run_id: 2c6b3e74ce784e819a696b40ed9473b7
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/832972020129942254/2c6b3e74ce784e819a696b40ed9473b7/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/832972020129942254/2c6b3e74ce784e819a696b40ed9473b7/artifacts/model
user_id: null
version: 4
