aliases: []
creation_timestamp: 1714922135495
current_stage: None
description: null
last_updated_timestamp: 1714922135495
name: AttentionUNet
run_id: 75e741d3d53b44da9808919f3a160ff7
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/795061038029973780/75e741d3d53b44da9808919f3a160ff7/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/795061038029973780/75e741d3d53b44da9808919f3a160ff7/artifacts/model
user_id: null
version: 4
