channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=24.2
- pip:
  - mlflow==2.11.0
  - astunparse==1.6.3
  - cloudpickle==3.0.0
  - numpy==1.24.3
  - optree==0.12.1
  - packaging==23.0
  - pandas==1.5.3
  - pynvml==11.4.1
  - pyyaml==6.0
  - torch==2.4.0
  - tqdm==4.66.4
name: mlflow-env
