aliases: []
creation_timestamp: 1713630750905
current_stage: None
description: null
last_updated_timestamp: 1713630750905
name: R2AttU_Net
run_id: 653c9c4e31c840d1a35a382ef852fe86
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/228065571089710161/653c9c4e31c840d1a35a382ef852fe86/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/228065571089710161/653c9c4e31c840d1a35a382ef852fe86/artifacts/model
user_id: null
version: 2
