artifact_uri: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/993479011557489331/fca5aa2a96ca4d9a8d930ee1fc0252d4/artifacts
end_time: 1715532179901
entry_point_name: ''
experiment_id: '993479011557489331'
lifecycle_stage: active
run_id: fca5aa2a96ca4d9a8d930ee1fc0252d4
run_name: UNet_MFCCs 2 seconds learning decay
run_uuid: fca5aa2a96ca4d9a8d930ee1fc0252d4
source_name: ''
source_type: 4
source_version: ''
start_time: 1715529060746
status: 3
tags: []
user_id: zainhazzouri
