aliases: []
creation_timestamp: 1724733553411
current_stage: None
description: null
last_updated_timestamp: 1724733553411
name: R2U_Net
run_id: 91d930b70d3a456fb0b5955e4a603fee
run_link: null
source: /home/zhazzouri/speech-music-classification-unet//mlflow/220170297150334846/91d930b70d3a456fb0b5955e4a603fee/artifacts/model
status: READY
status_message: null
storage_location: /home/zhazzouri/speech-music-classification-unet//mlflow/220170297150334846/91d930b70d3a456fb0b5955e4a603fee/artifacts/model
user_id: null
version: 3
