aliases: []
creation_timestamp: 1717396445124
current_stage: None
description: null
last_updated_timestamp: 1717396445124
name: R2AttU_Net
run_id: 16a574a44ed04c90b1483a5bb49944a5
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/109204143006382398/16a574a44ed04c90b1483a5bb49944a5/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/109204143006382398/16a574a44ed04c90b1483a5bb49944a5/artifacts/model
user_id: null
version: 4
