aliases: []
creation_timestamp: 1713566682586
current_stage: None
description: null
last_updated_timestamp: 1713566682586
name: R2U_Net
run_id: 17da9fa28f0642c9bf14e6a1a27e89d1
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/439015367249026603/17da9fa28f0642c9bf14e6a1a27e89d1/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/439015367249026603/17da9fa28f0642c9bf14e6a1a27e89d1/artifacts/model
user_id: null
version: 1
