artifact_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/776088093512842013
creation_time: 1717372782355
experiment_id: '776088093512842013'
last_update_time: 1717528957095
lifecycle_stage: deleted
name: AttentionR2UNet_Delta_Delta
tags: {}
