aliases: []
creation_timestamp: 1713563311509
current_stage: None
description: null
last_updated_timestamp: 1713563311509
name: AttentionUNet
run_id: 03e3ee506b5c4869b09f13db617fd4fd
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/104247588398260324/03e3ee506b5c4869b09f13db617fd4fd/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/104247588398260324/03e3ee506b5c4869b09f13db617fd4fd/artifacts/model
user_id: null
version: 1
