aliases: []
creation_timestamp: 1717324822688
current_stage: None
description: null
last_updated_timestamp: 1717324822688
name: AttentionUNet
run_id: 6743cb0d790b4c3fbcdf1f2144aea7a0
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/538854334497955759/6743cb0d790b4c3fbcdf1f2144aea7a0/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/538854334497955759/6743cb0d790b4c3fbcdf1f2144aea7a0/artifacts/model
user_id: null
version: 1
