aliases: []
creation_timestamp: 1717345624226
current_stage: None
description: null
last_updated_timestamp: 1717345624226
name: AttentionUNet
run_id: d98ec0d785c64764a3b9d0effd811a7b
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/490226126731308717/d98ec0d785c64764a3b9d0effd811a7b/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/490226126731308717/d98ec0d785c64764a3b9d0effd811a7b/artifacts/model
user_id: null
version: 2
