artifact_uri: /home/zhazzouri/speech-music-classification-unet//mlflow/119682144716302520/58afd8a82c3b447cadc90c87a26dcac1/artifacts
end_time: 1723037462544
entry_point_name: ''
experiment_id: '119682144716302520'
lifecycle_stage: active
run_id: 58afd8a82c3b447cadc90c87a26dcac1
run_name: R2UNet_MFCCs_80_features_30_seconds
run_uuid: 58afd8a82c3b447cadc90c87a26dcac1
source_name: ''
source_type: 4
source_version: ''
start_time: 1723025878451
status: 4
tags: []
user_id: zhazzouri
