channels:
- conda-forge
dependencies:
- python=3.10.11
- pip<=23.1.2
- pip:
  - mlflow==2.11.3
  - cloudpickle==3.0.0
  - numpy==1.24.3
  - packaging==23.0
  - pandas==1.5.3
  - pyyaml==6.0
  - torch==2.1.0.dev20230618
  - tqdm==4.65.0
name: mlflow-env
