aliases: []
creation_timestamp: 1715542867403
current_stage: None
description: null
last_updated_timestamp: 1715542867403
name: U_Net
run_id: ba6c19146be74ef1bb71eaf453efb3b3
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/993479011557489331/ba6c19146be74ef1bb71eaf453efb3b3/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/993479011557489331/ba6c19146be74ef1bb71eaf453efb3b3/artifacts/model
user_id: null
version: 7
