artifact_uri: /home/zhazzouri/speech-music-classification-unet//mlflow/385624305023984721/8b49e36dbeff45cd86d3b40f32e5c63e/artifacts
end_time: 1724686803760
entry_point_name: ''
experiment_id: '385624305023984721'
lifecycle_stage: active
run_id: 8b49e36dbeff45cd86d3b40f32e5c63e
run_name: U_Net_delta-delta_32_len5S
run_uuid: 8b49e36dbeff45cd86d3b40f32e5c63e
source_name: ''
source_type: 4
source_version: ''
start_time: 1724686455799
status: 3
tags: []
user_id: zhazzouri
