aliases: []
creation_timestamp: 1724731972673
current_stage: None
description: null
last_updated_timestamp: 1724731972673
name: AttentionUNet
run_id: dba57ce112364d959a661f98e9ef5aff
run_link: null
source: /home/zhazzouri/speech-music-classification-unet//mlflow/467833824249002624/dba57ce112364d959a661f98e9ef5aff/artifacts/model
status: READY
status_message: null
storage_location: /home/zhazzouri/speech-music-classification-unet//mlflow/467833824249002624/dba57ce112364d959a661f98e9ef5aff/artifacts/model
user_id: null
version: 5
