aliases: []
creation_timestamp: 1717381696229
current_stage: None
description: null
last_updated_timestamp: 1717381696229
name: R2U_Net
run_id: d7557aafcff744cca036a60f294092f9
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/219711652665281297/d7557aafcff744cca036a60f294092f9/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/219711652665281297/d7557aafcff744cca036a60f294092f9/artifacts/model
user_id: null
version: 4
