aliases: []
creation_timestamp: 1724733916244
current_stage: None
description: null
last_updated_timestamp: 1724733916244
name: R2U_Net
run_id: 334496dcaf494eddade276904b9de1d4
run_link: null
source: /home/zhazzouri/speech-music-classification-unet//mlflow/351730484888198486/334496dcaf494eddade276904b9de1d4/artifacts/model
status: READY
status_message: null
storage_location: /home/zhazzouri/speech-music-classification-unet//mlflow/351730484888198486/334496dcaf494eddade276904b9de1d4/artifacts/model
user_id: null
version: 4
