artifact_uri: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/993479011557489331/fb4bcb4c7b0d4153bdbafae1cf15d587/artifacts
end_time: 1715702420348
entry_point_name: ''
experiment_id: '993479011557489331'
lifecycle_stage: active
run_id: fb4bcb4c7b0d4153bdbafae1cf15d587
run_name: UNet_MFCCs 150 ms seconds learning decay
run_uuid: fb4bcb4c7b0d4153bdbafae1cf15d587
source_name: ''
source_type: 4
source_version: ''
start_time: 1715702412149
status: 4
tags: []
user_id: zainhazzouri
