aliases: []
creation_timestamp: 1713650400111
current_stage: None
description: null
last_updated_timestamp: 1713650400111
name: U_Net
run_id: 096ef0be7c4d4a2f89f664202bdb319d
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/134047778973749664/096ef0be7c4d4a2f89f664202bdb319d/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/134047778973749664/096ef0be7c4d4a2f89f664202bdb319d/artifacts/model
user_id: null
version: 3
