artifact_uri: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/594388770498243975/cbd7f629ee9f4e8fb7c51aca3e12fbd9/artifacts
end_time: 1717360432881
entry_point_name: ''
experiment_id: '594388770498243975'
lifecycle_stage: active
run_id: cbd7f629ee9f4e8fb7c51aca3e12fbd9
run_name: UNet_Delta_Delta
run_uuid: cbd7f629ee9f4e8fb7c51aca3e12fbd9
source_name: ''
source_type: 4
source_version: ''
start_time: 1717356462363
status: 3
tags: []
user_id: zainhazzouri
