aliases: []
creation_timestamp: 1717390862239
current_stage: None
description: null
last_updated_timestamp: 1717390862239
name: R2AttU_Net
run_id: 9335b65bfb1343929c24fa4bfd8486a4
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/109204143006382398/9335b65bfb1343929c24fa4bfd8486a4/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/109204143006382398/9335b65bfb1343929c24fa4bfd8486a4/artifacts/model
user_id: null
version: 3
