aliases: []
creation_timestamp: 1724726596708
current_stage: None
description: null
last_updated_timestamp: 1724726596708
name: R2AttU_Net
run_id: faa4de3735b943e3b2fe62ef6e295cb9
run_link: null
source: /home/zhazzouri/speech-music-classification-unet//mlflow/748767098654237839/faa4de3735b943e3b2fe62ef6e295cb9/artifacts/model
status: READY
status_message: null
storage_location: /home/zhazzouri/speech-music-classification-unet//mlflow/748767098654237839/faa4de3735b943e3b2fe62ef6e295cb9/artifacts/model
user_id: null
version: 3
