aliases: []
creation_timestamp: 1724743928158
current_stage: None
description: null
last_updated_timestamp: 1724743928158
name: U_Net
run_id: 242d3642f5b749afaeba67a182aca3ac
run_link: null
source: /home/zhazzouri/speech-music-classification-unet//mlflow/249598858612524705/242d3642f5b749afaeba67a182aca3ac/artifacts/model
status: READY
status_message: null
storage_location: /home/zhazzouri/speech-music-classification-unet//mlflow/249598858612524705/242d3642f5b749afaeba67a182aca3ac/artifacts/model
user_id: null
version: 16
