aliases: []
creation_timestamp: 1724728589465
current_stage: None
description: null
last_updated_timestamp: 1724728589465
name: U_Net
run_id: 0afec90a28a644da815517c233cd1538
run_link: null
source: /home/zhazzouri/speech-music-classification-unet//mlflow/204745828989228488/0afec90a28a644da815517c233cd1538/artifacts/model
status: READY
status_message: null
storage_location: /home/zhazzouri/speech-music-classification-unet//mlflow/204745828989228488/0afec90a28a644da815517c233cd1538/artifacts/model
user_id: null
version: 8
