aliases: []
creation_timestamp: 1715557796305
current_stage: None
description: null
last_updated_timestamp: 1715557796305
name: U_Net
run_id: eb80e7e5bc6c4c82b9c89ee3a9feb5cd
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/993479011557489331/eb80e7e5bc6c4c82b9c89ee3a9feb5cd/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/993479011557489331/eb80e7e5bc6c4c82b9c89ee3a9feb5cd/artifacts/model
user_id: null
version: 9
