aliases: []
creation_timestamp: 1715528889638
current_stage: None
description: null
last_updated_timestamp: 1715528889638
name: U_Net
run_id: 99f505bf21e245c8baa0e8ce89b5186f
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/993479011557489331/99f505bf21e245c8baa0e8ce89b5186f/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/993479011557489331/99f505bf21e245c8baa0e8ce89b5186f/artifacts/model
user_id: null
version: 4
