aliases: []
creation_timestamp: 1717377836903
current_stage: None
description: null
last_updated_timestamp: 1717377836903
name: U_Net
run_id: 7055069b1d5a4f55bdfc8cc2bd0ffe35
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/520261003477901015/7055069b1d5a4f55bdfc8cc2bd0ffe35/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/520261003477901015/7055069b1d5a4f55bdfc8cc2bd0ffe35/artifacts/model
user_id: null
version: 4
