aliases: []
creation_timestamp: 1715720471534
current_stage: None
description: null
last_updated_timestamp: 1715720471534
name: U_Net
run_id: 4ae3da92f33c49bfa2142c3ecbe80152
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/993479011557489331/4ae3da92f33c49bfa2142c3ecbe80152/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/993479011557489331/4ae3da92f33c49bfa2142c3ecbe80152/artifacts/model
user_id: null
version: 11
