aliases: []
creation_timestamp: 1724729752466
current_stage: None
description: null
last_updated_timestamp: 1724729752466
name: U_Net
run_id: 8e926b267f0844aba58d4a59e5e67d01
run_link: null
source: /home/zhazzouri/speech-music-classification-unet//mlflow/673814934802694760/8e926b267f0844aba58d4a59e5e67d01/artifacts/model
status: READY
status_message: null
storage_location: /home/zhazzouri/speech-music-classification-unet//mlflow/673814934802694760/8e926b267f0844aba58d4a59e5e67d01/artifacts/model
user_id: null
version: 11
