aliases: []
creation_timestamp: 1713572953387
current_stage: None
description: null
last_updated_timestamp: 1713572953387
name: R2AttU_Net
run_id: b07a680f3c444938ae2e5d01b2f7dcab
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/450552195002809623/b07a680f3c444938ae2e5d01b2f7dcab/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/450552195002809623/b07a680f3c444938ae2e5d01b2f7dcab/artifacts/model
user_id: null
version: 1
