aliases: []
creation_timestamp: 1715708090237
current_stage: None
description: null
last_updated_timestamp: 1715708090237
name: U_Net
run_id: 80a007f25f224fa3bd5f6aea3f40656a
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/993479011557489331/80a007f25f224fa3bd5f6aea3f40656a/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/993479011557489331/80a007f25f224fa3bd5f6aea3f40656a/artifacts/model
user_id: null
version: 10
