aliases: []
creation_timestamp: 1724729369835
current_stage: None
description: null
last_updated_timestamp: 1724729369835
name: U_Net
run_id: fc8b0f0c52824446912f4e95b4cf1204
run_link: null
source: /home/zhazzouri/speech-music-classification-unet//mlflow/505740359078139179/fc8b0f0c52824446912f4e95b4cf1204/artifacts/model
status: READY
status_message: null
storage_location: /home/zhazzouri/speech-music-classification-unet//mlflow/505740359078139179/fc8b0f0c52824446912f4e95b4cf1204/artifacts/model
user_id: null
version: 10
