aliases: []
creation_timestamp: 1715277471249
current_stage: None
description: null
last_updated_timestamp: 1715277471249
name: AttentionUNet
run_id: 7cc536a9d2fc4d3cafc6e8476751d328
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/878479630140196288/7cc536a9d2fc4d3cafc6e8476751d328/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/878479630140196288/7cc536a9d2fc4d3cafc6e8476751d328/artifacts/model
user_id: null
version: 6
