aliases: []
creation_timestamp: 1724687815782
current_stage: None
description: null
last_updated_timestamp: 1724687815782
name: U_Net
run_id: 1a08a42dfbbb4bdaa4260699d2c80bed
run_link: null
source: /home/zhazzouri/speech-music-classification-unet//mlflow/305258381259569180/1a08a42dfbbb4bdaa4260699d2c80bed/artifacts/model
status: READY
status_message: null
storage_location: /home/zhazzouri/speech-music-classification-unet//mlflow/305258381259569180/1a08a42dfbbb4bdaa4260699d2c80bed/artifacts/model
user_id: null
version: 6
