aliases: []
creation_timestamp: 1715537209687
current_stage: None
description: null
last_updated_timestamp: 1715537209687
name: U_Net
run_id: 9c770b44a3a947e38d8e38adfe674cfe
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/993479011557489331/9c770b44a3a947e38d8e38adfe674cfe/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/993479011557489331/9c770b44a3a947e38d8e38adfe674cfe/artifacts/model
user_id: null
version: 6
