artifact_uri: /home/zhazzouri/speech-music-classification-unet//mlflow/305258381259569180/1a08a42dfbbb4bdaa4260699d2c80bed/artifacts
end_time: 1724687816273
entry_point_name: ''
experiment_id: '305258381259569180'
lifecycle_stage: active
run_id: 1a08a42dfbbb4bdaa4260699d2c80bed
run_name: U_Net_lfcc-delta-delta_32_len5S
run_uuid: 1a08a42dfbbb4bdaa4260699d2c80bed
source_name: ''
source_type: 4
source_version: ''
start_time: 1724687470213
status: 3
tags: []
user_id: zhazzouri
