artifact_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/878479630140196288
creation_time: 1715273067677
experiment_id: '878479630140196288'
last_update_time: 1715273067677
lifecycle_stage: active
name: AttentionUNet_LFCCs_delta_delta
