aliases: []
creation_timestamp: 1714925656043
current_stage: None
description: null
last_updated_timestamp: 1714925656043
name: R2U_Net
run_id: dfefc7eb251046ceaebd52dd26be7c8e
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/321330964037417919/dfefc7eb251046ceaebd52dd26be7c8e/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/321330964037417919/dfefc7eb251046ceaebd52dd26be7c8e/artifacts/model
user_id: null
version: 5
