aliases: []
creation_timestamp: 1724734283515
current_stage: None
description: null
last_updated_timestamp: 1724734283515
name: R2U_Net
run_id: f7964b33e80e49b7bd37c5d9bf68b33c
run_link: null
source: /home/zhazzouri/speech-music-classification-unet//mlflow/164514431985969153/f7964b33e80e49b7bd37c5d9bf68b33c/artifacts/model
status: READY
status_message: null
storage_location: /home/zhazzouri/speech-music-classification-unet//mlflow/164514431985969153/f7964b33e80e49b7bd37c5d9bf68b33c/artifacts/model
user_id: null
version: 5
