aliases: []
creation_timestamp: 1724731302086
current_stage: None
description: null
last_updated_timestamp: 1724731302086
name: AttentionUNet
run_id: 04a528ffadec4327ad717f88be6cb06a
run_link: null
source: /home/zhazzouri/speech-music-classification-unet//mlflow/778618181404205111/04a528ffadec4327ad717f88be6cb06a/artifacts/model
status: READY
status_message: null
storage_location: /home/zhazzouri/speech-music-classification-unet//mlflow/778618181404205111/04a528ffadec4327ad717f88be6cb06a/artifacts/model
user_id: null
version: 3
