aliases: []
creation_timestamp: 1713655104084
current_stage: None
description: null
last_updated_timestamp: 1713655104084
name: AttentionUNet
run_id: 3a620a6b1b904256944babb4fbe077d0
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/208348904117728054/3a620a6b1b904256944babb4fbe077d0/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/208348904117728054/3a620a6b1b904256944babb4fbe077d0/artifacts/model
user_id: null
version: 3
