artifact_uri: /home/zhazzouri/speech-music-classification-unet//mlflow/983643993131039407/76e9bd74d51d473da738d3e8ceb3bbab/artifacts
end_time: 1724743026758
entry_point_name: ''
experiment_id: '983643993131039407'
lifecycle_stage: active
run_id: 76e9bd74d51d473da738d3e8ceb3bbab
run_name: U_Net_delta_32_len30S
run_uuid: 76e9bd74d51d473da738d3e8ceb3bbab
source_name: ''
source_type: 4
source_version: ''
start_time: 1724742592125
status: 3
tags: []
user_id: zhazzouri
