aliases: []
creation_timestamp: 1724686448799
current_stage: None
description: null
last_updated_timestamp: 1724686448799
name: U_Net
run_id: 3f1d18cf809949df97559ada15da0c92
run_link: null
source: /home/zhazzouri/speech-music-classification-unet//mlflow/720534821381005285/3f1d18cf809949df97559ada15da0c92/artifacts/model
status: READY
status_message: null
storage_location: /home/zhazzouri/speech-music-classification-unet//mlflow/720534821381005285/3f1d18cf809949df97559ada15da0c92/artifacts/model
user_id: null
version: 2
