aliases: []
creation_timestamp: 1717341812939
current_stage: None
description: null
last_updated_timestamp: 1717341812939
name: U_Net
run_id: 8acb6776e3bd4d0c885b1c8a50c914e3
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/551708483854750648/8acb6776e3bd4d0c885b1c8a50c914e3/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/551708483854750648/8acb6776e3bd4d0c885b1c8a50c914e3/artifacts/model
user_id: null
version: 2
