aliases: []
creation_timestamp: 1713607461607
current_stage: None
description: null
last_updated_timestamp: 1713607461607
name: R2U_Net
run_id: f0582b76e6e74fa483d65dbd603bbea8
run_link: null
source: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/439015367249026603/f0582b76e6e74fa483d65dbd603bbea8/artifacts/model
status: READY
status_message: null
storage_location: /Users/zainhazzouri/projects/Bachelor_Thesis/mlflow/439015367249026603/f0582b76e6e74fa483d65dbd603bbea8/artifacts/model
user_id: null
version: 2
